apiVersion: v1
kind: Service
metadata:
    name: "akswangyao1121-c983"
    labels:
        app: "akswangyao1121-c983"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "akswangyao1121-c983"